### ISSUE TITLE
Executing command  "npm run dev" on Windows generates error message

### ISSUE THREAD

**Issue by SusanneCalderon** [adempiere/adempiere-vue#1288]
#### Steps to reproduce

1. Download and Install nodes.js on Windows, 64 bit version
2. Install Vue/Cli with command _npm install -g @vue/cli_
3. Install Service with command _npm install @vue/cli-service -g_
4. Change directory to local Vue Project
5. Execute command npm run dev

#### Screenshot 
Error message on execute npm run dev
![imagen](https://user-images.githubusercontent.com/15349639/137712421-38679924-1045-4c8c-8e7e-948a23f2a497.png)

The following commands work on Linux, but not on Windows.
![imagen](https://user-images.githubusercontent.com/15349639/137712815-63ea08cf-f553-44cc-977b-00a722917943.png)

#### Expected behavior
I expect that the commands of file package.json work on Windows same as on Linux

#### Other relevant information
- Your OS: Windows 10
- Node.js version: v14.18.1
- adempiere-vue version: 4.4.0"

**Comment by EdwinBetanc0urt** [comment]
Greetings @SusanneCalderon, by the folders that are displayed in your project, it is missing the dependencies and libraries (a folder named node_modules). Run `yarn install`, and once the dependencies are installed re-run `npm run dev` or `yarn dev` again.

We recommend using yarn for the installation of project dependencies due to multiple issues we have had with npm. If you do not have yarn installed please see this page https://classic.yarnpkg.com/lang/en/docs/install/.

**Comment by SusanneCalderon** [comment]
@EdwinBetanc0urt , now it works perfectly. Thank you
