### ISSUE TITLE
POS Payment with Crédit Card (mandatory Fields)

### ISSUE THREAD

**Issue by niclopup** [adempiere/adempiere-vue#1361]
The payment with Credit Card now it demands to put a Credit Card Number and a Bank Account.

I think that the Number of the credit card could not be mandatory (and perhaps not even show it).

The same with the Bank Account, it shouldn't ask for it or at least don't be mandatory field.

![Campos Obligatorios Cobro POS Tarjeta de Crédito](https://user-images.githubusercontent.com/31936815/141485196-4faf2b17-5c47-47a7-9ab0-c4b91f545ceb.png)

**Comment by rcapecce** [comment]
Hi, I am reviewing the files involved, and from what I see in the fieldsListCollections.js file, when they are displayed and when they are required it is being hardcoded.

We are going to change the card number and the bank so that they are not mandatory.

In the event that you want it to be mandatory or not for some cases, we could evaluate adding checks to the C_POSPaymentTypeAllocation table

(proposed column names are debatable)
* isDisplayC_Bank_ID
* isMandatoryC_Bank_ID
* isDisplayCreditCardNumber
* isMandatoryCreditCardNumber
